server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users/xuyuancheng/projects/study/cloud/confsvr/src/main/resources/config/licensingservice




